apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: wiki-js-postgres
  labels:
    app: wiki-js
    component: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wiki-js
      component: database
  template:
    metadata:
      labels:
        app: wiki-js
        component: database
    spec:
      containers:
      - name: wiki-js-postgres
        image: postgres:9-alpine
        imagePullPolicy: IfNotPresent # Always
        env:
        - name: POSTGRES_USER
          value: wikijs
        - name: POSTGRES_PASSWORD
          value: wikijspassword
        - name: POSTGRES_DB
          value: wikijs
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-data
      volumes:
      - name: postgres-data
        emptyDir: {}