apiVersion: v1
kind: Service
metadata:
  name: wiki-js
spec:
  selector:
    app: wiki-js
    component: wiki
  type: NodePort
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30000